version: 2
jobs:
  install-site:
    docker:
      - image: node:8.9.4-alpine
    steps:
      - checkout
      - run:
          name: Add Dependencies
          command: apk add --no-cache curl git
      - run:
          name: Install & Build Project luna-site
          command: cd luna-frontend && yarn install && CI=false yarn build
  
  test-lint-site:
    docker:
      - image: node:8.9.4-alpine
    steps:
      - checkout
      - run:
          name: Add Dependencies
          command: apk add --no-cache curl git
      - run:
          name: Install & Build Project luna-site
          command: cd luna-frontend && yarn install && CI=false yarn build
      - run: 
          name: Test-lint Project
          command: echo "This Test-lint Space"

  test-unit-site:
    docker:
      - image: node:8.9.4-alpine
    steps:
      - checkout
      - run:
          name: Add Dependencies
          command: apk add --no-cache curl git
      - run:
          name: Install & Build Project luna-site
          command: cd luna-frontend && yarn install && CI=false yarn build
      - run: 
          name: Test-unit Project
          command: echo "This Test-unit Space"
        
  test-coverage-site:
    docker:
      - image: node:8.9.4-alpine
    steps:
      - checkout
      - run:
          name: Add Dependencies
          command: apk add --no-cache curl git
      - run:
          name: Install & Build Project luna-site
          command: cd luna-frontend && yarn install && CI=false yarn build
      - run: 
          name: Test-coverage Project
          command: echo "This Test-coverage Space"      
          
  install-api:
    docker:
      - image: node:8.9.4-alpine
    steps:
      - checkout
      - run:
          name: Add Dependencies
          command: apk add --no-cache curl git
      - run:
          name: Install & Build project luna-api
          command: cd luna-api && yarn install 
   
  test-lint-api:
    docker:
      - image: node:8.9.4-alpine
    steps:
      - checkout
      - run:
          name: Add Dependencies
          command: apk add --no-cache curl git
      - run:
          name: Install & Build project luna-api
          command: cd luna-api && yarn install
      - run: 
          name: Test-lint Project
          command: echo "This Test-lint Space"

  test-unit-api:
    docker:
      - image: node:8.9.4-alpine
    steps:
      - checkout
      - run:
          name: Add Dependencies
          command: apk add --no-cache curl git
      - run:
          name: Install & Build project luna-api
          command: cd luna-api && yarn install
      - run: 
          name: Test-unit Project
          command: echo "This Test-unit Space"
            
  test-coverage-api:
    docker:
      - image: node:8.9.4-alpine
    steps:
      - checkout
      - run:
          name: Add Dependencies
          command: apk add --no-cache curl git
      - run:
          name: Install & Build project luna-api
          command: cd luna-api && yarn install
      - run: 
          name: Test-coverage Project
          command: echo "This Test-coverage Space"

  build-docker-site:
    docker:
      - image: node:8.9.4-alpine
    steps:
      - checkout
      - run:
          name: Add Dependencies
          command: apk add --no-cache curl git
      - run:
          name: Install & Build Project luna-site
          command: cd luna-frontend && yarn install && CI=false yarn build
      - setup_remote_docker: 
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.12.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: 
          name: Build and Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t penthaizza/lunaproject:$(echo "site-"$(git rev-parse --short HEAD)) ./luna-frontend
            docker tag penthaizza/lunaproject:$(echo "site-"$(git rev-parse --short HEAD)) penthaizza/lunaproject:site-latest
            docker push penthaizza/lunaproject
  build-docker-api:
    docker:
      - image: node:8.9.4-alpine
    steps:
      - checkout
      - run:
          name: Add Dependencies
          command: apk add --no-cache curl git
      - run:
          name: Install & Build Project luna-site
          command: cd luna-frontend && yarn install && CI=false yarn build
      - setup_remote_docker: 
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.12.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: 
          name: Build and Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t penthaizza/lunaproject:$(echo "api-"$(git rev-parse --short HEAD)) ./luna-api
            docker tag penthaizza/lunaproject:$(echo "api-"$(git rev-parse --short HEAD)) penthaizza/lunaproject:api-latest 
            docker push penthaizza/lunaproject
                        
  deploy-to-dev:
    machine: true
    steps:
      - run: 
          name: Deploy to DEV-Site-Server
          command: | 
            sudo apt-get update
            sudo apt-get install sshpass
            sudo sshpass -p $PASS_SERVER ssh -o StrictHostKeyChecking=no $USER_SERVER@$SERVER_HOST "ls -a && sudo docker rm -f luna-site && sudo docker image prune -a -f && sudo docker run -d -p 3000:3000 -p 22200:22200 -p 17000:17000 --name luna-site penthaizza/lunaproject:site-latest"
      - run:
          name: Deploy to DEV-API-Server
          command: sudo sshpass -p $PASS_SERVER ssh -o StrictHostKeyChecking=no $USER_SERVER@$SERVER_HOST "ls -a && sudo docker rm -f luna-api && sudo docker image prune -a -f && sudo docker run -d -e "PORT=3020" -e "PROJECT_NAME=luna-api" -p 3020:3020 -p 22202:22202 -p 17002:17002 --name luna-api penthaizza/lunaproject:api-latest"
  
  deploy-to-prod-site:
    machine: true
    steps:
      - run: 
          name: Deploy to Prod-Site-Server
          command: | 
            sudo apt-get update
            sudo apt-get install sshpass
            sudo sshpass -p $PASS_SERVER ssh -o StrictHostKeyChecking=no $USER_SERVER@$PROD_SERVER "ls -a && sudo docker rm -f luna-site && sudo docker image prune -a -f && sudo docker run -d -p 3000:3000 -p 22200:22200 -p 17000:17000 --name luna-site penthaizza/lunaproject:site-latest"
  deploy-to-prod-api:
    machine: true
    steps:
      - run:
          name: Deploy to Prod-API-Server
          command: sudo sshpass -p $PASS_SERVER ssh -o StrictHostKeyChecking=no $USER_SERVER@$PROD_SERVER "ls -a && sudo docker rm -f luna-api && sudo docker image prune -a -f && sudo docker run -d -e "PORT=3020" -e "PROJECT_NAME=luna-api" -p 3020:3020 -p 22202:22202 -p 17002:17002 --name luna-api penthaizza/lunaproject:api-latest"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - install-site:
          filters:
            branches:
                only: 
                  - develop
                  - master
      - install-api:
          filters:
            branches:
                only:
                  - develop
                  - master
      - test-lint-site:
          requires:
            - install-site
          filters:
            branches:
                only:
                  - develop
                  - master
      - test-unit-site:
          requires:
            - test-lint-site
          filters:
            branches:
                only: 
                  - develop
                  - master
      - test-coverage-site:
          requires:
            - test-unit-site
          filters:
            branches:
                only:
                  - develop
                  - master
      
      - test-lint-api:
          requires:
            - install-api
          filters:
            branches:
                only:
                  - develop
                  - master
      - test-unit-api:
          requires:
            - test-lint-api
          filters:
            branches:
                only:
                  - develop
                  - master
      - test-coverage-api:
          requires:
            - test-unit-api
          filters:
            branches:
                only:
                  - develop
                  - master
      
      - deploy-to-dev:
          requires:
            - install-site
            - test-lint-site
            - test-unit-site
            - test-coverage-site
            - install-api
            - test-lint-api
            - test-unit-api
            - test-coverage-api
          filters:
            branches:
                only:
                  - develop
                  - master
      - deploy-to-prod-site:
          requires:
            - deploy-to-dev
          filters:
            branches:
                only: master
      - deploy-to-prod-api:
          requires:
            - deploy-to-dev
          filters:
            branches:
                only: master