version: 2
jobs:
  build:
    docker:
      - image: node:8.9.4-alpine
    steps:
      - checkout
      - run:
          name: Add Dependencies
          command: apk add --no-cache curl
      - run:
          name: Install & Build Project luna-site
          command: cd luna-frontend && yarn install && CI=false yarn build 
      - run:
          name: Install & Build project luna-api
          command: cd luna-api && yarn install
      - run: 
          name: Test Project
          command: echo "This Test Space"
      - setup_remote_docker: 
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.12.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: 
          name: Build and Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t penthaizza/lunaproject:$SITE_TAG ./luna-frontend
            docker build -t penthaizza/lunaproject:$API_TAG ./luna-api
            docker push penthaizza/lunaproject:$SITE_TAG
            docker push penthaizza/lunaproject:$API_TAG
  deploy:
    machine: true
    steps:
      - run: 
          name: Deploy to Site-Server
          command: | 
            sudo apt-get update
            sudo apt-get install sshpass
            sudo sshpass -p $PASS_SERVER ssh -o StrictHostKeyChecking=no $USER_SERVER@$SERVER_HOST "ls -a && sudo docker stop luna-site && sudo docker rm luna-site && sudo docker rmi penthaizza/lunaproject:$SITE_TAG && sudo docker pull penthaizza/lunaproject:$SITE_TAG && sudo docker run -d -p 3000:3000 -p 22200:22200 -p 17000:17000 --name luna-site penthaizza/lunaproject:$SITE_TAG"
      - run:
          name: Deploy to API-Server
          command: sudo sshpass -p $PASS_SERVER ssh -o StrictHostKeyChecking=no $USER_SERVER@$SERVER_HOST "ls -a && sudo docker stop luna-api && sudo docker rm luna-api && sudo docker rmi penthaizza/lunaproject:$API_TAG && sudo docker pull penthaizza/lunaproject:$API_TAG && sudo docker run -d -e "PORT=3020" -e "PROJECT_NAME=luna-api" -p 3020:3020 -p 22202:22202 -p 17002:17002 --name luna-api penthaizza/lunaproject:$API_TAG"
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
                only: develop