nodeimage: &nodeimage
  docker:
    - image: node:8.9.4-alpine
pythonimage: &pythonimage
  docker:
    - image: circleci/python:3.7
nodedepend: &nodedepend
  run:
    name: Add Dependencies
    command: apk add --no-cache curl git
installsandy: &installsandy
  run:
    name: Install & Build Project luna-sandy
    command: cd luna-sandy && yarn install
installdocker: &installdocker
  run:
    name: Install Docker client
    command: |
      set -x
      VER="18.03.1-ce"
      curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
      tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      mv /tmp/docker/* /usr/bin
filterrepo: &filterrepo
  branches:
    only:
      - develop
      - master
filterprod: &filterprod
  requires:
    - deploy-to-dev
  filters:
    branches:
      only: master

version: 2
jobs:
  build-docker-gateway:
    <<: *pythonimage
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          name: Install pipenv
          command: |
            cd luna-gateway
            sudo pip install pipenv
            pipenv install --dev
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t penthaizza/lunaproject:$(echo "api-"$(git rev-parse --short HEAD)) ./luna-gateway
            docker tag penthaizza/lunaproject:$(echo "api-"$(git rev-parse --short HEAD)) penthaizza/lunaproject:api-latest 
            docker push penthaizza/lunaproject
  build-docker-sandy:
    <<: *nodeimage
    steps:
      - checkout
      - *nodedepend
      - *installsandy
      - setup_remote_docker:
          docker_layer_caching: true
      - *installdocker
      - run:
          name: Build and Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t penthaizza/lunaproject:$(echo "sandy-"$(git rev-parse --short HEAD)) ./luna-sandy
            docker tag penthaizza/lunaproject:$(echo "sandy-"$(git rev-parse --short HEAD)) penthaizza/lunaproject:sandy-latest
            docker push penthaizza/lunaproject

  deploy-to-dev:
    machine: true
    steps:
      - run:
          name: Deploy to DEV-Gateway&Sandy-Server BangmodCloud
          command: |
            sudo apt-get update
            sudo apt-get install sshpass
            sudo sshpass -p $PASS_SERVER ssh -o StrictHostKeyChecking=no $LUNA_USER@$LUNA_SERVER "ls -a && sudo screen -d -m -S Gateway /root/luna-api/swarm/deploy-swarm.sh"
  deploy-to-prod-gateway:
    machine: true
    steps:
      # - run:
      #     name: Deploy to Prod-Gateway&Sandy-Server
      #     command: |
      #       sudo apt-get update
      #       sudo apt-get install sshpass
      #       sudo sshpass -p $PASS_SERVER ssh -o StrictHostKeyChecking=no $LUNA_USER@$LUNA_SERVER "ls -a && sudo screen -d -m -S Gateway /root/luna-api/swarm/deploy-swarm.sh"
      - run:
          name: Deploy to DEV-Gateway Metrabyte
          command: |
            sudo apt-get update
            sudo apt-get install sshpass
            sudo sshpass -p $PASS_SERVER ssh -o StrictHostKeyChecking=no $USER_ADMIN@$SERVER "ls -a && sudo screen -d -m -S API ./deploy-api.sh"
      - run:
          name: Deploy to DEV-Sandy Metrabyte
          command: sudo sshpass -p $PASS_SERVER ssh -o StrictHostKeyChecking=no $USER_ADMIN@$SERVER "ls -a && sudo screen -d -m -S Sandy ./deploy-sandy.sh"
  # deploy-to-prod-sandy:
  #   machine: true
  #   steps:
  #     - run:
  #         name: Deploy to Prod-Sandy-Server
  #         command: sudo sshpass -p $PASS_SERVER ssh -o StrictHostKeyChecking=no $USER_SERVER@$PROD_SERVER "ls -a && sudo docker rm -f luna-sandy && sudo docker image prune -a -f && sudo docker run -d -p 127.0.0.1:3020:3020 --name luna-sandy-1 penthaizza/lunaproject:sandy-latest" && sudo docker run -d -p 127.0.0.1:17003:17003 --name luna-sandy-2 penthaizza/lunaproject:sandy-latest" && sudo docker run -d -p 127.0.0.1:22203:22203 --name luna-sandy-3 penthaizza/lunaproject:sandy-latest"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-docker-gateway:
          filters: *filterrepo

      - build-docker-sandy:
          filters: *filterrepo

      - deploy-to-dev:
          requires:
            - build-docker-gateway
            - build-docker-sandy
          filters: *filterrepo
      - deploy-to-prod-gateway: *filterprod
      # - deploy-to-prod-sandy: *filterprod
